import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const base = pathToFileURL(resolve('dist/index.html')).href + '?autostart=1&q=low&nolock=1';
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(base + '&mode=infection');
await page.waitForFunction(() => window.__game && window.__game.playing, null, { timeout: 60000 });
await page.waitForTimeout(400);
const r = await page.evaluate(() => {
  const g = window.__game, rules = g.woz.rules, p = g.player;
  g.fastForward(20, 1 / 30);
  rules.phase = 'battle'; rules.phaseTimeLeft = 999; g.timeLeft = 999;
  const v = g.actors.find((a) => a.alive && a !== p && a.id < rules.playerCount && rules.state(a.id).side === 'human');
  rules.convertToMutant(v.id, 'nightrunner', false);
  g.woz.convertNow(v, true);
  v.pos.set(-8, 0.1, 0); v.protectT = 0; v.armor = 0;
  g.fastForward(0.3, 1 / 30);
  const e0 = rules.humanEnergy(p.id);
  g.damage(v, p, 30, 'chest', 'ak47', { x: 1, z: 0 }, false);
  g.fastForward(0.2, 1 / 30);
  return { e0: +e0.toFixed(2), e1: +rules.humanEnergy(p.id).toFixed(2), vHp: v.hp, vAlive: v.alive, pAlive: p.alive };
});
console.log(JSON.stringify(r));
await browser.close();
