import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const base = pathToFileURL(resolve('dist/index.html')).href + '?autostart=1&q=low&nolock=1';
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(base + '&mode=infection');
await page.waitForFunction(() => window.__game && window.__game.playing, null, { timeout: 60000 });
await page.waitForTimeout(400);
const r = await page.evaluate(() => {
  const g = window.__game, rules = g.woz.rules, p = g.player;
  g.fastForward(20, 1 / 30);
  rules.phase = 'battle'; rules.phaseTimeLeft = 999; g.timeLeft = 999;
  rules.convertToMutant(p.id, 'tangler', false);
  g.woz.convertNow(p, true);
  p.pos.set(5, 0.1, 0); p.yaw = Math.PI / 2; p.pitch = 0; p.protectT = 999;
  if (p.vel.set) p.vel.set(0, 0, 0);
  const v = g.actors.find((a) => a.alive && a !== p && a.id < rules.playerCount && rules.state(a.id).side === 'human');
  if (!v) return { ok: false };
  v.pos.set(0, 0.1, 0); v.protectT = 0;
  g.fastForward(1 / 30, 1 / 30);
  p.updateCamera(0.016);
  const s1 = { charge: +rules.state(p.id).skillCharge.toFixed(2) };
  const used1 = rules.tryUseSkill(p.id);
  const s2 = { charge: +rules.state(p.id).skillCharge.toFixed(2), active: rules.state(p.id).skillActive };
  g.fastForward(6.2, 1 / 30);
  const s3 = { charge: +rules.state(p.id).skillCharge.toFixed(2), phase: rules.phase, alive: p.alive, humans: rules.humansAlive() };
  const refired = rules.tryUseSkill(p.id);
  rules.convertToMutant(p.id, 'souleater', false);
  g.woz.convertNow(p, true);
  const fin = rules.finishRound; rules.finishRound = () => {};
  const used2 = rules.tryUseSkill(p.id);
  const s4 = { charge: +rules.state(p.id).skillCharge.toFixed(2), active: rules.state(p.id).skillActive };
  g.fastForward(3.2, 1 / 30);
  const c1 = +rules.state(p.id).skillCharge.toFixed(2);
  g.fastForward(5, 1 / 30);
  const c2 = +rules.state(p.id).skillCharge.toFixed(2);
  rules.finishRound = fin;
  return { s1, used1, s2, s3, refired, used2, s4, c1, c2 };
});
console.log(JSON.stringify(r, null, 1));
await browser.close();
