import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const b = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = await b.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)));
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE:', m.text().slice(0, 160)); });
await page.goto(pathToFileURL(resolve('dist/index.html')).href + '?autostart=1&q=low&nolock=1&mode=confront');
await page.waitForTimeout(6000);
console.log('playing:', await page.evaluate(() => window.__game?.playing).catch((e) => 'evalfail ' + e.message.slice(0, 80)));
await b.close();
